config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => "pages#contact"
  match '/about',   :to => "pages#about"
  match '/help',    :to => "pages#help"
  match '/signup',  :to => "users#new"
  match '/signin',  :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"

end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    %h2 #{pluralize(object.errors.count, "error")} prohibited this #{object.class.to_s.underscore.humanize.downcase} from being saved
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %table.microposts{:summary => "Status feed"}
    = render :partial => "shared/feed_item", :collection => @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%tr
  %td.gravatar
    = link_to gravatar_for(feed_item.user), feed_item.user
  %td.micropost
    %span.user
      = link_to feed_item.user.name, feed_item.user
    %span.content
      = feed_item.content
    %span.timestamp
      Posted
      = time_ago_in_words(feed_item.created_at)
      ago
  - if current_user?(feed_item.user)
    %td
      = link_to 'delete', feed_item, :method => :delete,
        :confirm => "Are you sure?",
        :title => feed_item.content

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.text_area :content
  .actions
    = f.submit "Submit"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %table{:summary => "User stats"}
    %tr
      %td
        %a{:href => "#{following_user_path(@user)}"}
          %span#following.stat
            = "#{@user.following.count} following"
      %td
        %a{:href => "#{followers_user_path(@user)}"}
          %span#followers.stat
            = pluralize(@user.followers.count, "follower")

app/views/shared/_user_info.html.haml
.user_info
  %a{:href => "#{user_path(current_user)}"}
    = gravatar_for current_user, :size => 30
    %span.user_name= current_user.name
    %span.microposts= pluralize(current_user.microposts.count, "micropost")