config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => "pages#contact"
  match '/about',   :to => "pages#about"
  match '/help',    :to => "pages#help"
  match '/signup',  :to => "users#new"
  match '/signin',  :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"

end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to "Contact", contact_path
      %li= link_to "News", "http://news.railstutorial.org/"
      %li= link_to "About", about_path

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav.round
    %ul
      %li= link_to "Home", root_path
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign Out", signout_path
        %li= link_to "Profile", user_path(current_user)
        %li= link_to "Users", users_path
        %li= link_to "Settings", edit_user_path(current_user)
      - else
        %li= link_to "Sign In", signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    "application", :media => "screen"
    = stylesheet_link_tag    "print", :media => "print"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9]
      %script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}
    /[if lt IE 8]
      = stylesheet_link_tag "ie", :media => "screen"
  %body
    .container
      = render 'layouts/header'
      %section.round
        - flash.each do |key, value|
          .flash{:class => "#{key}"}= value
        = yield
      = render 'layouts/footer'
      = debug params if Rails.env.development?